#!/usr/bin/env python

import broker
import broker.bro
import time
import uuid
from ipaddress import *

# Create endpoint & subscribers.
endpoint = broker.Endpoint()
subscriber = endpoint.make_subscriber(["/vast/control"])
endpoint.listen("127.0.0.1", 43000)
# Loop until peering established successfully.
while True:
    print("waiting for commands")
    (topic, data) = subscriber.get()
    event = broker.bro.Event(data)
    (qid, expression) = event.args()
    # Answer the query with dummy data
    make_result_event = lambda *xs: broker.bro.Event("VAST::result", qid, *xs)
    generate_data = lambda x: [x, time.ctime(), [IPv4Address("10.0.0.1")]]
    for x in map(generate_data, range(10)):
        endpoint.publish("/vast/data", make_result_event(x))
    endpoint.publish("/vast/data", make_result_event(None))
